# ===================================================================
# CONFIGURACION GLOBAL DEL PROYECTO
# Sistema de deteccion de fraude en tiempo real
# ===================================================================

# ---------------------------------------------------
#  Rutas de datos del Data Lake (Medallion Architecture)
# ---------------------------------------------------
paths:

  # -------------------------------
  # Carpeta general de logs
  # -------------------------------
  logs:
    root: "logs/"

  # -------------------------------
  # Capa RAW (entrada original)
  # -------------------------------
  data_raw:
    root: "data/raw/"

    datasets:
      root: "data/raw/datasets/"
      paysim: "data/raw/datasets/PaySim1.csv"

  # -------------------------------
  # Capa BRONZE (datos limpiados sin transformar)
  # -------------------------------
  data_bronze:
    root: "data/bronze/"
    paysim_cash_in_parquet: "data/bronze/paysim_cash_in.parquet"
    paysim_cash_out_parquet: "data/bronze/paysim_cash_out.parquet"
    paysim_debit_parquet: "data/bronze/paysim_debit.parquet"
    paysim_payment_parquet: "data/bronze/paysim_payment.parquet"
    paysim_transfer_parquet: "data/bronze/paysim_transfer.parquet"

  # -------------------------------
  # Capa SILVER (datos transformados / agregados)
  # -------------------------------
  data_silver:
    root: "data/silver/"

  # -------------------------------
  # Capa GOLD (datos para consumo final / BI / ML)
  # -------------------------------
  data_gold:
    root: "data/gold/"

# ---------------------------------------------------
#  Configuración de Logging global
# ---------------------------------------------------
logging:
  level: "INFO"
  logs_dir: "logs"
  producer_log: "logs/producer/producer.log"
  spark_log: "logs/spark/structured_streaming.log"
  api_log: "logs/api/api_access.log"

# ---------------------------------------------------
#  Configuración del Generador de Transacciones (Producer)
# ---------------------------------------------------

# ---------------------------------------------------
#  Configuración de Kafka
# ---------------------------------------------------
kafka:
  broker: "${KAFKA_ADVERTISED_LISTENERS}"
  zookeeper: "${KAFKA_ZOOKEEPER_CONNECT}"
  topics:
    - "paysim_cash_in"
    - "paysim_cash_out"
    - "paysim_debit"
    - "paysim_payment"
    - "paysim_transfer"
# ---------------------------------------------------
#  Configuración de Spark Structured Streaming
# ---------------------------------------------------

# ---------------------------------------------------
#  Configuración de PostgreSQL
# ---------------------------------------------------

