# ===================================================================
# CONFIGURACION GLOBAL DEL PROYECTO
# Sistema de deteccion de fraude en tiempo real
# ===================================================================

# ---------------------------------------------------
#  Rutas de datos del Data Lake (Medallion Architecture)
# ---------------------------------------------------
paths:

  # -------------------------------
  # Carpeta general de logs
  # -------------------------------
  logs:
    root: "logs/"

  # -------------------------------
  # Capa RAW (entrada original)
  # -------------------------------
  data_raw:
    root: "data/raw/"

    datasets:
      root: "data/raw/datasets/"
      paysim: "data/raw/datasets/PaySim1.csv"

  # -------------------------------
  # Capa BRONZE (datos limpiados sin transformar)
  # -------------------------------
  data_bronze:
    root: "data/bronze/"
    paysim_preprocessed: "data/bronze/paysim_preprocessed.parquet"

  # -------------------------------
  # Capa SILVER (datos transformados / agregados)
  # -------------------------------
  data_silver:
    root: "data/silver/"

  # -------------------------------
  # Capa GOLD (datos para consumo final / BI / ML)
  # -------------------------------
  data_gold:
    root: "data/gold/"

# ---------------------------------------------------
#  Configuración de Logging global
# ---------------------------------------------------
logging:
  level: "INFO"
  logs_dir: "logs"
  producer_log: "logs/producer/producer.log"
  spark_log: "logs/spark/structured_streaming.log"
  api_log: "logs/api/api_access.log"

# ---------------------------------------------------
#  Configuración del Generador de Transacciones (Producer)
# ---------------------------------------------------

# ---------------------------------------------------
#  Configuración de Kafka
# ---------------------------------------------------

# ---------------------------------------------------
#  Configuración de Spark Structured Streaming
# ---------------------------------------------------

# ---------------------------------------------------
#  Configuración de PostgreSQL
# ---------------------------------------------------

