version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "${ZK_PORT}:${ZK_PORT}"
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZK_PORT}
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ${KAFKA_DATA_DIR}/zookeeper:/var/lib/zookeeper/data
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_INTER_BROKER_LISTENER_NAME: ${KAFKA_INTER_BROKER_LISTENER_NAME}
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    volumes:
      - ${KAFKA_DATA_DIR}/kafka:/var/lib/kafka/data
    restart: unless-stopped

  spark-master:
    image: apache/spark:3.5.2
    container_name: spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    environment:
      SPARK_MASTER_HOST: spark-master
    ports:
      - "${SPARK_MASTER_PORT}:${SPARK_MASTER_PORT}"
      - "8080:8080"
    volumes:
      - ${SPARK_MASTER_LOGS}:/opt/spark/logs
    restart: unless-stopped

  spark-worker:
    image: apache/spark:3.5.2
    container_name: spark-worker
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:${SPARK_MASTER_PORT}"]
    depends_on:
      - spark-master
    volumes:
      - ${SPARK_WORKER_LOGS}:/opt/spark/logs
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - ${MONGO_DATA_DIR}:/data/db
    restart: unless-stopped

volumes:
  spark_master:
  spark_worker:
  mongo:
  kafka:
